version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    image: prxveen/xyzbookstore
    ports:
      - "5000:5000"
    depends_on:
      - db

